"""Configurações dos agentes e LLMs."""

from app.config.agents import (
    AMBIGUITY_RESOLVER_AGENT_CONFIG,
    CADASTRO_AGENT_CONFIG,
    CRITIC_AGENT_CONFIG,
    FINANCEIRO_AGENT_CONFIG,
    ORCHESTRATION_CONFIGS,
    PLANNER_AGENT_CONFIG,
    RENTABILIDADE_AGENT_CONFIG,
    RESPONSE_AGENT_CONFIG,
    THEME_CONFIGS,
    VISUALIZATION_AGENT_CONFIG,
    AgentConfig,
    get_agent_config,
    get_available_themes,
    get_theme_config,
    get_theme_descriptions,
)
from app.config.llm import create_llm
from app.config.models import (
    DEFAULT_MODEL,
    MODELS_REGISTRY,
    ModelConfig,
    ModelProvider,
    ModelTask,
    check_provider_available,
    get_available_models,
    get_model_config,
    get_model_display_info,
    get_models_by_provider,
)

__all__ = [
    "AgentConfig",
    "AMBIGUITY_RESOLVER_AGENT_CONFIG",
    "CADASTRO_AGENT_CONFIG",
    "FINANCEIRO_AGENT_CONFIG",
    "RENTABILIDADE_AGENT_CONFIG",
    "PLANNER_AGENT_CONFIG",
    "CRITIC_AGENT_CONFIG",
    "RESPONSE_AGENT_CONFIG",
    "VISUALIZATION_AGENT_CONFIG",
    "THEME_CONFIGS",
    "ORCHESTRATION_CONFIGS",
    "get_agent_config",
    "get_theme_config",
    "get_available_themes",
    "get_theme_descriptions",
    "MODELS_REGISTRY",
    "DEFAULT_MODEL",
    "ModelConfig",
    "ModelProvider",
    "ModelTask",
    "check_provider_available",
    "create_llm",
    "get_available_models",
    "get_model_config",
    "get_model_display_info",
    "get_models_by_provider",
]
